apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-greeter-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vgichira/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: simple-greeter

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
