apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-greeter-depl
  labels:
    app: simple-greeter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-greeter
  template:
    metadata:
      labels:
        app: simple-greeter
    spec:
      containers:
      - name: simple-greeter-api
        image: vgichira/simple_greeter-api:v1
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"